
title: Pavan Kumar Aryasomayajulu
url: 'http://xyzcoder.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Pavan Kumar Aryasomayajulu  ## put your name
title: 'Software &amp; Developer'  ## your title
location: Visakhapatnam , India


## Social Profiles
facebook: https://www.facebook.com/paryasomayajulu  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/pavankumararya/  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
